variables:
  CONTAINER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_BUILD_REF_NAME}_${CI_BUILD_REF} | tr '[:upper:]' '[:lower:]'
  CONTAINER_IMAGE_LATEST: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest | tr '[:upper:]' '[:lower:]'

services:
  - docker:dind #Start the docker daemon

stages: #declare the stages to task
  - build-docker-image
  
build-docker: #builds the docker image for the release
  stage: build-docker-image
  image: docker:latest
  
  script:
    - cd ./hellonode
    - echo "CONAINER_IMAGE:" ${CONTAINER_IMAGE,,}
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CONTAINER_IMAGE,,} .
    - docker tag ${CONTAINER_IMAGE,,} ${CONTAINER_IMAGE_LATEST,,}
    - docker push ${CONTAINER_IMAGE,,}
    - docker push ${CONTAINER_IMAGE_LATEST,,}