apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    name: web-server
  name: web-server-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: web-server
    spec:
      containers:
        - name: node
          image: __IMAGETAG__
          ports: 
            - containerPort: 8080
              name: www
          env:
            - name: SERVER_ID  #export the pod ID as SERVER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
        readinessProbe: # time to come alive (only at startup)
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe: # check if app is alive (during executino)
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
      imagePullSecrets:
        - name: __IMAGESECRET__
---
apiVersion: v1 
kind: Service
metadata:
  labels:
    name: web-server
  name: web-server-service
spec:
  ports:
  - name: webserver
    port: 80
    targetPort: 8080
  selector:
    name: web-server
  type: LoadBalancer
